<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Actarius-MkII" ignored="0" name="Class Tests" tests="23" failures="8" timestamp="18 Apr 2018 22:21:13 GMT" time="0.056" errors="0">
  <testcase name="@BeforeMethod setUp" time="0.002" classname="test.TestCard">
    <failure type="java.io.FileNotFoundException" message="\resources\scripts\go-to-jail.lua (The system cannot find the path specified)">
      <![CDATA[java.io.FileNotFoundException: \resources\scripts\go-to-jail.lua (The system cannot find the path specified)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at core.Resources.stream(Unknown Source)
at core.Card.<init>(Unknown Source)
at test.TestCard.setUp(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="test.TestCard">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterClass tearDownAfterClass" time="0.0" classname="test.TestCard">
    <skipped/>
  </testcase> <!-- @AfterClass tearDownAfterClass -->
  <testcase name="@BeforeMethod setUp" time="0.001" classname="test.TestCardSpace">
    <failure type="java.io.FileNotFoundException" message="\resources\config\chance.json (The system cannot find the path specified)">
      <![CDATA[java.io.FileNotFoundException: \resources\config\chance.json (The system cannot find the path specified)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at core.Resources.stream(Unknown Source)
at core.CardSpace.parseConfig(Unknown Source)
at core.CardSpace.<init>(Unknown Source)
at test.TestCardSpace.setUp(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="test.TestCardSpace">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@BeforeMethod setUp" time="0.0" classname="test.TestCardSpace">
    <skipped/>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="test.TestCardSpace">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@BeforeMethod setUp" time="0.0" classname="test.TestCardSpace">
    <skipped/>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="test.TestCardSpace">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@BeforeMethod setUp" time="0.0" classname="test.TestCardSpace">
    <skipped/>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="test.TestCardSpace">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterClass tearDownAfterClass" time="0.0" classname="test.TestCardSpace">
    <skipped/>
  </testcase> <!-- @AfterClass tearDownAfterClass -->
  <testcase name="testGettersAndSetters" time="0.0" classname="test.TestCard">
    <skipped/>
  </testcase> <!-- testGettersAndSetters -->
  <testcase name="testCardCnt" time="0.0" classname="test.TestCardSpace">
    <skipped/>
  </testcase> <!-- testCardCnt -->
  <testcase name="testCardSprite" time="0.0" classname="test.TestCardSpace">
    <skipped/>
  </testcase> <!-- testCardSprite -->
  <testcase name="testDrawCard" time="0.0" classname="test.TestCardSpace">
    <skipped/>
  </testcase> <!-- testDrawCard -->
  <testcase name="testGetName" time="0.0" classname="test.TestCardSpace">
    <skipped/>
  </testcase> <!-- testGetName -->
  <testcase name="testGettersAndSetters" time="0.001" classname="test.TestDie">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at core.Sprite.getWidth(Unknown Source)
at core.Die.getWidth(Unknown Source)
at test.TestDie.testGettersAndSetters(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testGettersAndSetters -->
  <testcase name="testSetNum" time="0.0" classname="test.TestDie"/>
  <testcase name="testGiveMoney" time="0.0" classname="test.TestPlayer">
    <failure type="java.lang.AssertionError" message="expected [1500] but found [1499]">
      <![CDATA[java.lang.AssertionError: expected [1500] but found [1499]
at test.TestPlayer.testGiveMoney(Unknown Source)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGiveMoney -->
  <testcase name="testMiscSettersAndGetters" time="0.0" classname="test.TestPlayer"/>
  <testcase name="testProperties" time="0.001" classname="test.TestPlayer"/>
  <testcase name="testSetPlayerPos" time="0.0" classname="test.TestPlayer">
    <failure type="java.lang.AssertionError" message="expected [39] but found [-1]">
      <![CDATA[java.lang.AssertionError: expected [39] but found [-1]
at test.TestPlayer.testSetPlayerPos(Unknown Source)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testSetPlayerPos -->
  <testcase name="testSetTurnsLeftInJail" time="0.0" classname="test.TestPlayer">
    <failure type="java.lang.AssertionError" message="expected [1] but found [-1]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [-1]
at test.TestPlayer.testSetTurnsLeftInJail(Unknown Source)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testSetTurnsLeftInJail -->
  <testcase name="testTakeMoney" time="0.0" classname="test.TestPlayer">
    <failure type="java.lang.AssertionError" message="expected [500] but found [501]">
      <![CDATA[java.lang.AssertionError: expected [500] but found [501]
at test.TestPlayer.testTakeMoney(Unknown Source)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testTakeMoney -->
  <testcase name="testTurnsLeftInJail" time="0.0" classname="test.TestPlayer">
    <failure type="java.lang.AssertionError" message="expected [5] but found [-1]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [-1]
at test.TestPlayer.testTurnsLeftInJail(Unknown Source)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testTurnsLeftInJail -->
  <testcase name="testGetRent" time="0.0" classname="test.TestRailroadProperty"/>
  <testcase name="testGettersAndSetters" time="0.0" classname="test.TestRailroadProperty"/>
  <testcase name="testMiscSettersAndGetters" time="0.0" classname="test.TestSprite">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at core.Sprite.getWidth(Unknown Source)
at test.TestSprite.testMiscSettersAndGetters(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testMiscSettersAndGetters -->
  <testcase name="testSpriteManipulation" time="0.003" classname="test.TestSprite">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at core.ImageUtils.toBufferedImage(Unknown Source)
at core.ImageUtils.rotate(Unknown Source)
at core.Sprite.rotate(Unknown Source)
at test.TestSprite.testSpriteManipulation(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testSpriteManipulation -->
  <testcase name="testGettersAndSetters" time="0.0" classname="test.TestStandardProperty"/>
  <testcase name="testRent" time="0.0" classname="test.TestStandardProperty"/>
  <testcase name="testUpgradeAndDowngrade" time="0.0" classname="test.TestStandardProperty"/>
  <testcase name="testGetRent" time="0.0" classname="test.TestUtilityProperty"/>
  <testcase name="testGettersAndSetters" time="0.0" classname="test.TestUtilityProperty"/>
</testsuite> <!-- Class Tests -->
